<a href="https://colab.research.google.com/github/Thales-Gabriel-Soares-Amorim/Elimina-o-Gaussiana-e-Matriz-de-Hilbert/blob/main/Gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#eliminação gaussiana
import numpy as np
def gauss(A, b):
  # A é a matriz dos coeficientes
  # b é o vetor de termos independentes

  n = len(b) #definir tamanho

  for k in range (0, n-1): #percorre a diagonal
    pivo = A[k][k]

    for i in range (k+1, n): #percorre as linhas
      m = A[i][k] / pivo

      for j in range (k, n): #percorre as colunas
        A[i][j] = A[i][j] - m* A[k][j]

        b[i] = b[i] - m*b[k]

      return A, b # depois de feito o escalonamento


A = [3, 2, 4],[1, 1, 2],[4, 3, -2]
b = [1 , 2 , 3]

print(np.array(A_t))
print ("----------------")
print(b_t)

#x = a_maiusculo*b #A produto vetorial x = b
#x é o vetor solução, A é a matriz dos coeficientes, b é o vetor de termos independentes

# transformar A em A_tio  que é uma matriz trangular superior, fazer o mesmo com b

#selecionar o pivo do primeiro ate o penultimo

#para cada linha



#parte 2 substituição inversa
def susbtituicao_reversa(A_t, b_x):
  n = len(b)

  x = n*[0] #vetor solução

  x[n-1]= b_t[n-1] / A_t[n-1][n-1]

  for k in range (n-2,-1,-1): #percorre as linhas detras para frente
   s = 0
   for j in range (k+1,n):
    s = s + A_t[k]
  return x # retorna a solução do SL A*x=b

#teste
x = substituicao_reversa(A_t,b_t)
print (x)
def Hilbert(n):
  b = n*[0]

  A = n*[n*[0]]

  return A, b



#fazer de biblioteca e na atividade

[[ 3  2  4]
 [ 1  1  2]
 [ 4  3 -2]]
----------------
[1, 2, 3]


NameError: ignored

tem coisa para corrigir
